{
 "title": "Speedtest",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Last Download Speed ⬇",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Upload Speed ⬆",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Ping ⏱",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "query": "SELECT last(\"ping\") FROM \"speed_test_results\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "speedtest",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ping" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "data cap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "alias": "data used",
     "measurement": "comcast_data_usage",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "ch$tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"power\") FROM \"downstream_statistics\" WHERE $timeFilter GROUP BY time($__interval), \"channel\" fill(previous)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       { "params": [ "power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "ch$tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "ch$tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_statistics",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Corrected / Uncorrectables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ch$tag_channel",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" }
      ],
      [
       { "params": [ "corrected" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Comcast Outages",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "measurement": "logs",
     "query": "SELECT reason_detail AS \"Event\" FROM \"logs\" WHERE (\"friendlyname\" = 'edgerouter ping') AND $timeFilter ",
     "select": [
      [
       { "params": [ "reason_detail" ], "type": "field" },
       { "params": [ "blah" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "friendlyname", "operator": "=", "value": "edgerouter ping" }
     ]
    }
   ]
  }
 ]
}