apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: blackbox-exporter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-blackbox-exporter
    version: 1.6.0
  valuesFrom:
    - externalSourceRef:
        url: https://raw.githubusercontent.com/REBELinBLUE/k8s-on-hypriot/master/deployments/monitoring/blackbox-exporter/blackbox-exporter-values.yaml
